[koji]
allowed_domains = [ "osbuild.org", "client.osbuild.org", "localhost" ]
ca = "/etc/osbuild-composer/ca-crt.pem"

[worker]
allowed_domains = [ "osbuild.org", "client.osbuild.org", "localhost" ]
ca = "/etc/osbuild-composer/ca-crt.pem"
